### ISSUE TITLE
Import with Comfy-ui manager does not seem to work.

### ISSUE THREAD

**Issue by ryzen88** [civen-cn/ComfyUI-PaddleOcr#3]
Hey hello,
I wanted to try out your plugin, but after installing it in the manager it does not seem to work, i am guessing that the additional requirements do nog get installed. I am using the portable version of comfy ui so its not fully clear to me how to get it working now.

**Comment by ryzen88** [comment]
![req](https://github.com/user-attachments/assets/0ae51e14-e028-4509-afc3-ae258f5f6b65)
This seems to be the issue
requrements

**Comment by civen-cn** [comment]
> ![req](https://private-user-images.githubusercontent.com/111976708/374243658-0ae51e14-e028-4509-afc3-ae258f5f6b65.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTMzNTgsIm5iZiI6MTcyODM1MzA1OCwicGF0aCI6Ii8xMTE5NzY3MDgvMzc0MjQzNjU4LTBhZTUxZTE0LWUwMjgtNDUwOS1hZmMzLWFlMjU4ZjVmNmI2NS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwMjA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmRlNWRhNzNkZmFlZDlmMTQ1NjBkM2EyMzJjOTkyYThiNDFhN2E2YWQ1NmVhOTU0NWYwODliYjViODM4Y2IxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8258l22bDovipnqHwg0DjG9vYUJj-Nfn5sW6BBuKn8s) This seems to be the issue requrements

check the log of comfyui，maybe the node is not loaded

**Comment by ryzen88** [comment]
I did a non portable install of comfyui and after de fixed requirements name it still will not work

### Loading: ComfyUI-Manager (V2.51.4)
### ComfyUI Revision: 2745 [8dfa0cc5] | Released on '2024-10-07'
Traceback (most recent call last):
  File "E:\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI\custom_nodes\ComfyUI-PaddleOcr\__init__.py", line 1, in <module>
    from .paddle_ocr import *
  File "E:\ComfyUI\custom_nodes\ComfyUI-PaddleOcr\paddle_ocr.py", line 2, in <module>
    from paddleocr import PaddleOCR
  File "C:\Users\Admin\.conda\envs\comfyenv\Lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "C:\Users\Admin\.conda\envs\comfyenv\Lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
  File "C:\Users\Admin\.conda\envs\comfyenv\Lib\site-packages\paddle\__init__.py", line 28, in <module>
    from .base import core  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\.conda\envs\comfyenv\Lib\site-packages\paddle\base\__init__.py", line 39, in <module>
    from . import framework
  File "C:\Users\Admin\.conda\envs\comfyenv\Lib\site-packages\paddle\base\framework.py", line 40, in <module>
    from .proto import (
  File "C:\Users\Admin\.conda\envs\comfyenv\Lib\site-packages\paddle\base\proto\data_feed_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\Admin\.conda\envs\comfyenv\Lib\site-packages\google\protobuf\descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Cannot import E:\ComfyUI\custom_nodes\ComfyUI-PaddleOcr module for custom nodes: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by civen-cn** [comment]
> I did a non portable install of comfyui and after de fixed requirements name it still will not work
> 
> ### Loading: ComfyUI-Manager (V2.51.4)
> ### ComfyUI Revision: 2745 [8dfa0cc5] | Released on '2024-10-07'
> Traceback (most recent call last): File "E:\ComfyUI\nodes.py", line 1998, in load_custom_node module_spec.loader.exec_module(module) File "", line 995, in exec_module File "", line 488, in _call_with_frames_removed File "E:\ComfyUI\custom_nodes\ComfyUI-PaddleOcr__init__.py", line 1, in from .paddle_ocr import * File "E:\ComfyUI\custom_nodes\ComfyUI-PaddleOcr\paddle_ocr.py", line 2, in from paddleocr import PaddleOCR File "C:\Users\Admin.conda\envs\comfyenv\Lib\site-packages\paddleocr__init__.py", line 14, in from .paddleocr import * File "C:\Users\Admin.conda\envs\comfyenv\Lib\site-packages\paddleocr\paddleocr.py", line 21, in import paddle File "C:\Users\Admin.conda\envs\comfyenv\Lib\site-packages\paddle__init__.py", line 28, in from .base import core # noqa: F401 ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Admin.conda\envs\comfyenv\Lib\site-packages\paddle\base__init__.py", line 39, in from . import framework File "C:\Users\Admin.conda\envs\comfyenv\Lib\site-packages\paddle\base\framework.py", line 40, in from .proto import ( File "C:\Users\Admin.conda\envs\comfyenv\Lib\site-packages\paddle\base\proto\data_feed_pb2.py", line 36, in _descriptor.FieldDescriptor( File "C:\Users\Admin.conda\envs\comfyenv\Lib\site-packages\google\protobuf\descriptor.py", line 553, in **new** _message.Message._CheckCalledFromGeneratedFile() TypeError: Descriptors cannot be created directly. If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0. If you cannot immediately regenerate your protos, some other possible workarounds are:
> 
> 1. Downgrade the protobuf package to 3.20.x or lower.
> 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
> 
> More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
> 
> Cannot import E:\ComfyUI\custom_nodes\ComfyUI-PaddleOcr module for custom nodes: Descriptors cannot be created directly. If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0. If you cannot immediately regenerate your protos, some other possible workarounds are:
> 
> 1. Downgrade the protobuf package to 3.20.x or lower.
> 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

pip install protobuf==3.20.2

**Comment by ryzen88** [comment]
super thanks, that worked perfectly.
